# Generated by Django 6.0.2 on 2026-05-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0002_book_available_to_borrow_book_contributer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='contributer',
            new_name='contributor',
        ),
    ]
