# Generated by Django 6.0.2 on 2026-05-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Full'), ('C', 'Completed'), ('D', 'Discontinued')], default='O', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Full')], default='O', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
