# Generated by Django 6.0.2 on 2026-03-06 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['created_on'], 'verbose_name': 'commission', 'verbose_name_plural': 'commissions'},
        ),
        migrations.AlterModelOptions(
            name='commissiontype',
            options={'ordering': ['name'], 'verbose_name': 'commission type', 'verbose_name_plural': 'commission types'},
        ),
    ]
