# Generated by Django 6.0.2 on 2026-03-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_on'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['name'], 'verbose_name': 'event type', 'verbose_name_plural': 'event types'},
        ),
    ]
