# Generated by Django 6.0.2 on 2026-03-06 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0002_alter_event_options_alter_eventtype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['name'], 'verbose_name': 'event category', 'verbose_name_plural': 'event categories'},
        ),
    ]
